services:

### PHP-FPM Container #######################################

  php-fpm:
    container_name: php-fpm
    hostname: php-fpm
    image: php:7.2-alpine
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html

### NGINX Server Container ##################################

  nginx:
    depends_on:
      - php-fpm
      - mysql
    extra_hosts:
      - contacts.test:127.0.0.1
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://contacts.test/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    image: nginx:mainline-alpine
    links:
      - php-fpm
      - redis
    ports:
      - "80:80"
    volumes:
      - ./docker-config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      
### MySQL Container #########################################

  mysql:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=3019l^%jugjhfJYTHG65
      - MYSQL_DATABASE=contacts
      - MYSQL_USER=contacts
      - MYSQL_PASSWORD=JBYRYBVUuyftdo576545e^%

### REDIS Container #########################################

  redis:
    image: redis

version: "2.3"